### ISSUE TITLE
bug: Connector not found on Android

### ISSUE THREAD

**Issue by vildantursic** [wagmi-dev/wagmi#1325] opened 2022-11-17 21:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.5

### Current Behavior

MetaMask connector simple button throws error `Connector not found` ONLY on mobile phone (Android & iOS)

```
_app-f77e5d9e709838a4.js:25 Uncaught (in promise) ConnectorNotFoundError: Connector not found
    at MetaMaskConnector.connect (_app-f77e5d9e709838a4.js:25:21712)
    at async connectMetaMask (index-e44dbdce91f5ef1a.js:1:9662)
    ```
```

### Expected Behavior

It connects to MetaMask on mobile and returns wallet account

### Steps To Reproduce

Repo with simple code - (metamask branch)
https://github.com/vildantursic/test-wallet/tree/metamask

Deployed Demo app on Vercel **(RUN ON MOBILE)**
Just select **MetaMask** button
https://test-wallet-g058b7msq-vildantursic.vercel.app/
 

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://test-wallet-g058b7msq-vildantursic.vercel.app/

### Anything else?

_No response_

**Comment by tmm** [comment] 2022-11-18 00:11
Linking related issue https://github.com/wagmi-dev/wagmi/issues/838

**Comment by vildantursic** [comment] 2022-11-18 09:20
any news on this?

**Comment by jxom** [comment] 2022-11-19 04:20
Going to debug this on my Android device soon!

**Comment by vildantursic** [comment] 2022-11-20 20:55
Hey @jxom 
I just figured that issue is happening even if you simulate mobile device on Chrome 🙃.
(screenshot: https://prnt.sc/IWGlvSJn4lpC).

**Comment by jxom** [comment] 2022-11-20 22:52
Connecting via the MetaMask mobile browser works fine on both devices for me. Closing as I am unable to reproduce the issue. Please note that the `MetaMaskConnector` is an injected connector and utilizes the injected `window.ethereum`, so it won't work on a typical mobile browser (Chrome, Safari, etc) – it WILL work on the MetaMask mobile browser as they inject `window.ethereum`. 


https://user-images.githubusercontent.com/7336481/202930803-73ee8153-17b8-4ca8-af0d-ec219e53538e.MOV


https://user-images.githubusercontent.com/7336481/202930804-d32bf6c6-b094-4363-a515-ac68b614b487.mp4

**Closed by jxom** 2022-11-20 22:52 UTC

**Comment by vildantursic** [comment] 2022-11-21 07:37
Ahaam, got it! Thanx @jxom !
So it has to use Wallets browsers.
Is there any way to avoid using those wallet browsers and do similar to what WalletConnect is doing, redirecting user back to browser after he confirms connection?
