### ISSUE TITLE
bug: `shimDisconnectKey` of MetaMask injector is undefined

### ISSUE THREAD

**Issue by rafal2228** [wagmi-dev/wagmi#1871] opened 2023-02-17 09:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.11.5

### Current Behavior

`protected shimDisconnectKey` property defined on `InjectedConnector` class is not properly computed on the extending class level.

Note. this is not the case for `SafeConnector`, which redefines the above-mentioned property

### Expected Behavior

When logging in with `MetaMask` connector the property set in `storage` should be using a key containing `metaMask` injector name. Instead, the full key is computed as `wagmi.undefined.shimDisconnect` 

### Steps To Reproduce

1. Login with MetaMask connector using the official wagmi example
2. Inspect created keys in the LocalStorage 

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://wagmi.sh/examples/connect-wallet

### Anything else?

Browser: any

Screenshot:
![image](https://user-images.githubusercontent.com/9198051/219600628-f492805f-a17d-4164-89b7-f3656d47e81e.png)

It might be better to simply define this property as a getter function, to avoid extending it and allowing it to be properly computed when accessed

**Comment by tmm** [comment] 2023-02-17 14:26
Duplicate of https://github.com/wagmi-dev/references/issues/112

**Closed by tmm** 2023-02-17 14:26 UTC
