### ISSUE TITLE
bug: Cannot find module 'wagmi/connectors/injected' or its corresponding type declarations

### ISSUE THREAD

**Issue by MananTank** [wagmi-dev/wagmi#1849] opened 2023-02-14 06:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11.5

### Current Behavior

<img width="872" alt="image" src="https://user-images.githubusercontent.com/22043396/218656622-98407075-3867-49de-b481-69c420b95544.png">

### Steps To Reproduce

Just paste the code shown in docs on https://wagmi.sh/ homepage on codesandbox 
https://codesandbox.io/s/wagmi-ts-issue-mjp6db?file=/src/App.tsx

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/wagmi-ts-issue-mjp6db?file=/src/App.tsx

**Comment by hanahem** [comment] 2023-02-17 14:02
Getting the same issue with providers.

Same here:
wagmi: 0.11.5
ethers: 5

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/18723363/219676207-e3410729-e13b-410d-b7c0-a64608f55698.png">

**Comment by hanahem** [comment] 2023-02-17 21:57
> Getting the same issue with providers.
> 
> Same here: wagmi: 0.11.5 ethers: 5
> 
> <img alt="image" width="1001" src="https://user-images.githubusercontent.com/18723363/219676207-e3410729-e13b-410d-b7c0-a64608f55698.png">

That's fixed for me. My bad I was calling /publicProvider instead of /public.

**Comment by kseikyo** [comment] 2023-02-22 19:26
@MananTank Did you tried only using CRA and inside codesandbox? I tried locally using **pnpm** and it worked just fine on a new **next js** project with typescript.

I'm gonna try locally with npm, and later on CRA to see what is the root of the problem.

<img width="1108" alt="Screenshot 2023-02-22 at 16 16 47" src="https://user-images.githubusercontent.com/29212286/220735995-ac346d72-154f-41b3-a6d1-9e0bb43c5b62.png">

**Comment by kseikyo** [comment] 2023-02-22 19:53
In a create-react-app setup, [which is discouraged to use today](https://github.com/facebook/create-react-app/discussions/11768), the issue is solved by importing from:
`wagmi/dist/connectors/injected`

**Comment by tmm** [comment] 2023-03-03 19:34
Since wagmi doesn't officially support CRA and this doesn't appear to be an issue with other set ups, going to close this issue.

**Closed by tmm** 2023-03-03 19:34 UTC
