### ISSUE TITLE
bug: Field `data` from `useSigner` changes on subsequent calls of `useSigner`

### ISSUE THREAD

**Issue by afmfe-iul** [wagmi-dev/wagmi#987] opened 2022-09-22 17:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.7

### Current Behavior

Given a component that is always rendered and is performing side effects based on the `data` field from `useSigner`, I expect the side effects to run only when that field changes, however it seems that `data` is changing every time other components that also call `userSigner` are mounted. 

### Expected Behavior

It's expected that `useSigner().data` remains the same object across renders until it actually changes, so that it can be used in the dependencies array of react hooks like `useEffect` and `useCallback`. 

### Steps To Reproduce

1. Download the project from codesanbox;
2. Run `yarn` to install dependencies, followed by `yarn start`;
3. A browser tab will open (if not visit `http://localhost:3000/`), open the developer console, notice that every time the `show` button is clicked the component listening for changes on `useSigner().data` is triggered.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/wagmi-usesigner-bug-1gkexf

### Anything else?

Codesandbox doesn't support the sample code because it needs to be connect to an actual wallet to be reproducible, the project needs to be downloaded and run locally.
The project has 2 components:
- `UseSignerLogger` that is always rendered and contains a `useEffect` hook that logs a message to the console every time `useSigner().data` changes.
- `DummyUseSignerCaller` that also calls `useSigner()`, and is mounted or unmounted when a button is clicked.

`DummyUseSignerCaller` being mounted causes `UseSignerLogger` to detect a signer change everytime. 

Maybe issue #919 is related and the "looping re-renders" are a consequence of this field changing.

**Comment by afmfe-iul** [comment] 2022-10-05 09:55
Hey @jxom! Given this is a blocker for us currently, I'm wondering if you know when #1000 will be merged?

**Comment by jxom** [comment] 2022-10-05 20:23
It's merged now! Just gonna reopen this one until it's actually released.

**Comment by jxom** [comment] 2022-10-06 01:34
Published `0.6.8` that includes this fix!

**Closed by jxom** 2022-10-06 01:34 UTC

**Comment by madmarko** [comment] 2022-12-08 15:52
I believe this is back.

Using useSigner multiple times in different components, will trigger side effects if used as dependency.

i.e. if the data from `const { data } = useSigner()` is used as a useEffect dependency, and we've initialized a total of three signers, all in different components, the effect will run three times.

**Comment by tmm** [comment] 2022-12-08 16:18
@madmarko what version are you using?

**Comment by madmarko** [comment] 2022-12-08 16:23
Hi @tmm, I'm using the latest stable release at the time of writing, 0.9.0

**Comment by jxom** [comment] 2022-12-08 20:00
@madmarko – I am unable to reproduce this, even with that Sandbox you provided.

The original issue was that the effect in `UseSignerLogger` was being called when a `useSigner` was initialized in `DummyUseSignerCaller`. I can't seem to replicate this again.

However, I am noticing a separate issue where `useSigner` initializes with `undefined`, and then sets its value to `null` if no signer is instantiated. I'd expect this to always be `null` until a signer is instantiated. Is this along the lines of the bug you are experiencing?

**Comment by madmarko** [comment] 2022-12-08 20:29
@jxom - unfortunately it's a little bit difficult to provide a sandbox for.
It's not a strict mode issue as I have it turned off in our application.

Essentially where you see the multiple undefined initializations, I get:
- from: undefined to: RpcProvider
- from RpcProvider to: RpcProvider
- from RpcProvider to: RpcProvider

I will do my best to try and provide a sandbox.

**Comment by jxom** [comment] 2022-12-08 20:49
That would be great! Thank you.

**Comment by madmarko** [comment] 2022-12-08 21:54
@jxom - I've only been able to make it happen one extra time on CodeSandbox, though in our app it's happening once or twice more as it's being used way more:
https://codesandbox.io/s/confident-babbage-4cvv1z
(please also check the console output for useWhyDidYouUpdate)

For context:
Our scenario is that on page load (or on request), we'd be making an Api call that would give us back the string content of the message that subsequently needs to be signed.

We need the signer as a dependency in the effect that would ultimately call the functions that fetches data from the Api, in order to know if the signer's been initialized. (we also have other dependencies that must be truthy.)

For the record I've also seen useSignMessage but I'm unable to pass it to my external service that makes the Api calls as it's a hook, and the Api calls are being made outside of React context.

So what happens now is, we get the Api call fired multiple time because of the signer update, where all other dependencies are fine.
We're currently working around it with useState, but that's messy.

**Comment by tomiiide** [comment] 2023-11-30 16:30
@madmarko I'm currently dealing with this issue, did #1447  fix it for you?

if no how did you fix it?

**Comment by madmarko** [comment] 2023-11-30 17:34
@tomiiide it seemed to be fixed in a new release around January this year. Unfortunatley we also did an overhaul at the time - I am no longer working on it so I cannot provide more detailed info, sorry!
