### ISSUE TITLE
bug: UseContractRead with watch set to True fires an extra eth_call

### ISSUE THREAD

**Issue by missphyrgames** [wagmi-dev/wagmi#1035] opened 2022-10-02 10:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.7

### Current Behavior

I'm not certain this is a bug, however, I have this code
```
    const { data: totalSupplyData } = useContractRead({
        ...contractConfig,
        functionName: 'totalSupply',
        watch: true,
    })
```
If watch is set to false, there are 2 requests made that I can see in the network inspector: an `eth_blockNumber` and an `eth_call`. However, when I set watch to True, I see 3 requests are made: an `eth_blockNumber` and 2 `eth_call`. Is this the intended behaviour? The calls that are made after are all 2 requests so that's fine but it's just that initial request has 3 calls. I would have thought it should always be 2 requests to read a value from the contract but would love your thoughts on this!

### Expected Behavior

Expected 2 requests to be made initially and at every interval based on the pollingInterval.

### Steps To Reproduce

Set watch to True in useContractRead and inspect the network calls being made.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/blue-waterfall-k9cg34?file=/pages/index.tsx

**Comment by jxom** [comment] 2022-10-05 23:56
Hi! Seems like your example is broken because Alchemy has deprecated Rinkeby now 😅 

I tried to reproduce this issue on mainnet & goerli, but no success. 

I'm gonna close this one for now, but if you are still encountering this issue on another chain, can you update your Sandbox? I can re-open if this is still an issue!

**Closed by jxom** 2022-10-05 23:56 UTC
