### ISSUE TITLE
Calling the contract prompts an error that the gas cannot be estimatedbug: <title>

### ISSUE THREAD

**Issue by yjjdick** [wagmi-dev/wagmi#1863] opened 2023-02-15 18:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.9.0

### Current Behavior

![image](https://user-images.githubusercontent.com/8224370/219121667-32956e8f-3f99-41ab-baf7-1618511b2a50.png)
Here is the method to call
`try {
        const config = await prepareWriteContract({
          address: myRouterContractAddr,
          abi: require("@/abi/fengshu.json"),
          functionName: 'fastSell',
          args: [pancakeContractAddr, _this.tokenContractAddr, lpContractChecksumAddr, exchangeAmount],
        })
        const data = await writeContract(config)
        this.successHash = data.hash
        let hash = data.hash
        const waitdata = await waitForTransaction({
          hash
        })

        if (waitdata.status == 0 || !waitdata.status) {
          _this.txStatus = 0
        } else {
          _this.txStatus = 1
        }
        if (_this.txStatus == 0) {
          $("#modal-danger").modal("show");
        } else {
          $("#modal-success").modal("show");
          _this.getTokenBalance()
        }

      } catch (e) {
        console.error(e)
        if (e.message.indexOf("User rejected request") > -1) {
          Toast.warning("操作取消")
          return
        }

        _this.trySellMsg = e.message
      }`
Please tell me how to modify this code to solve the problem of error

**Comment by jxom** [comment] 2023-02-15 20:14
Closing as dupe of #1862.

**Closed by jxom** 2023-02-15 20:14 UTC
