### ISSUE TITLE
WC v2 Proposal namespaces with respect of smart contract wallets

### ISSUE THREAD

**Issue by niallkh** [wagmi-dev/wagmi#2542] opened 2023-06-13 12:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.1.0

### Current Behavior

More users currently are starting using smart contract wallets multichain, especially safe multisig. Smart contract wallet can be deployed selectively on specific chain. Current configuration of WalletConnectConnector doesn't respect this and sends ethereum mainnet as required network. Dapp should be able to work equally on different chains without specifying required network. Because smart contract wallet may be not deployed on required chain, but deployed on optional chains. Wallet can't continue working with dapp because it violates wallet connect protocol [2.4. Session Namespaces MUST contain at least one account in requested chains.](https://docs.walletconnect.com/2.0/specs/clients/sign/namespaces#24-session-namespaces-must-contain-at-least-one-account-in-requested-chains)

Code responsible for selecting required and optional chains:
```
const [defaultChain, ...optionalChains] = this.chains.map(({ id }) => id)
...
         chains: [defaultChain],
         optionalChains: optionalChains,
```

### Expected Behavior

Dapp should be able to send proposal with empty required chains and not empty optional chains.
From dapp development perspective I think that required chains make sense in rare cases, for instance, if dapp's contracts are deployed only on one chain. When dapp works on several chains it doesn't make sense to provide them as required because wallet may be deployed only in part of them, they should be provided as optional.

For instance, if dapp configures 1 chain then it should be required. If dapp configures several chains then all chains should be optional.

### Anything else?

https://github.com/wagmi-dev/references/issues/330

**Comment by tmm** [comment] 2023-06-13 13:15
Duplicate of https://github.com/wagmi-dev/references/issues/330. Let's just keep one issue open to track.

**Closed** 2023-06-13 13:16 UTC
