### ISSUE TITLE
I want to use @wagmi/core to build the connector of walletconnetct, but if I scan the code or cannot find the login, the mobile phone will directly crash back when the code is scanned

### ISSUE THREAD

**Issue by youthinn** [wagmi-dev/wagmi#2323] opened 2023-05-12 06:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.2

### Current Behavior

![image](https://github.com/wagmi-dev/wagmi/assets/96770326/6077b5fd-ccca-4f82-b6a9-a6a54b818cab)
The provided example is also in this situation, how can I solve it?

### Expected Behavior

What I want to implement is the connection between metamask and coinbase and walletconnect wallet, and the wallet of the walletconnect connector can be customized, how to solve it?

**Comment by jxom** [comment] 2023-05-12 06:44
dupe of #2322

**Closed by jxom** 2023-05-12 06:44 UTC
