### ISSUE TITLE
bug: `request` property is undefined in the return value of usePrepareContractWrite()

### ISSUE THREAD

**Issue by mr-new-0509** [wagmi-dev/wagmi#2608] opened 2023-06-24 06:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.2.1

### Current Behavior

const { config } = usePrepareContractWrite({
    address: USDT_CONTRACT_ADDRESS,
    abi: USDT_CONTRACT_ABI,
    functionName: 'transfer',
    args: [CONTRACT_ADDRESS, Number(parseUnits(`${Number(debouncedSellAmount)}`, 6))],
    chainId: CHAIN_ID,
});

This is my code.
`config` has `request` property as you know.
The problem is that the value of the `request` property is `undefined` when I built the code, but not in dev mode.
The framework I'm using is React `v18.2.0`, and Node.js environment is Node `v18.16.0`.

### Expected Behavior

The value of the `request` property should be an object, not `undefined`.

**Comment by jxom** [comment] 2023-06-25 03:10
`request` is undefined when the Prepare step is idle or has errored. It can be idle when: your wallet is not connected, or one of the Hook parameters (`address`, `abi`, or `functionName`) is undefined. Looks like the former doesn't apply to you, so is your wallet connected, or did an error occur (you can check with the returned `error` value)?

Closing for now. If it's still an issue, please open a new issue and provide a minimal reproducible example via https://new.wagmi.sh.

**Closed by jxom** 2023-06-25 03:10 UTC
