### ISSUE TITLE
bug:  usePreparedContractWrite locks browser window

### ISSUE THREAD

**Issue by chrysb** [wagmi-dev/wagmi#899] opened 2022-08-29 22:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.6.4

### Current Behavior

```
    const { config, error } = usePrepareContractWrite({
      addressOrName: collectionAddress,
      enabled: false,
      contractInterface: erc721ABI,
      functionName: 'setApprovalForAll',
      args: [OPENSEA_CONDUIT_ADDRESS, true],
    })
  ```
  
When I refresh the page or after a hot reload, the browser freezes but doesn't take up CPU. Eventually after 30 seconds it gets through. When I uncomment this, it no longer happens. Upon a performance inspection, it looks like it might be related to `REACT_QUERY` which is not something I'm familiar with, and something we don't use directly here.

For now, I'm going to go the `recklesslyUnprepared` route.

### Expected Behavior

I would expect the browser window not to freeze.

### Anything else?

Chrome MacOS
React v17

**Comment by phumaster** [comment] 2022-08-30 10:11
I think you're facing the same issue with me https://github.com/wagmi-dev/wagmi/issues/891. I have created a new project and tried to reproduce this case. But unfortunately, It's not happened. So `wagmi` may not be the root cause. Now I'm trying to find out the problem :(

**Comment by jxom** [comment] 2022-08-30 11:59
@chrysb — any chance you can post a reproducible example? Here is a CodeSandbox template: https://codesandbox.io/s/serene-morse-frzh0w

**Comment by aramalipoor** [comment] 2022-08-30 15:17
If it helps we had a similar situation and it was because `wagmi.cache` grew too big, and after removing it (or simply clearing all the storage) it was back to normal.

It could be related, but not sure :)

**Comment by jxom** [comment] 2022-08-30 22:24
Closing for now until a reproducible example is provided.

If the cache is growing too big, you may need to use a different persister or disable some queries with `cacheTime: 0`.

**Closed by jxom** 2022-08-30 22:24 UTC

**Comment by jxom** [comment] 2022-08-31 11:46
https://github.com/wagmi-dev/wagmi/discussions/880#discussioncomment-3516226 may also be related. Will take a closer look at this.
