### ISSUE TITLE
bug: Empty tab created on chrome with wallet connect

### ISSUE THREAD

**Issue by gilles-hemmerle** [wagmi-dev/wagmi#1713] opened 2023-01-24 10:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.10.10

### Current Behavior

When you want to use wallet connect on your mobile device, and choose a wallet (example metamask), it creates a blank page on chrome after the metamask connection.

### Expected Behavior

The user should be redirected to the initial page instead of a blank page.

### Steps To Reproduce

- Use a dapp implementing wagmi on chrome / brave on Chrome
- Connect with wallet connect
- Click the connect button
- it opens a blank tab and then android ask you which wallet you want to use
- Choose metamask
- Accept connection
- Get redirected to your browser
- You are now redirected to a blank page

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://ve32i9.csb.app/

### Anything else?

Maybe linked with this ticket reported on the walletconnect's github:
https://github.com/WalletConnect/walletconnect-monorepo/issues/1027#issuecomment-1176980414

**Comment by jxom** [comment] 2023-01-25 21:42
Yeah, I'd say this issue is a dupe of https://github.com/WalletConnect/walletconnect-monorepo/issues/1027#issuecomment-1176980414. Maybe we can track this there instead?

Might be worth looking into WalletConnect v2 as well (I think this issue would be solved)!

**Closed by jxom** 2023-01-25 21:42 UTC
