### ISSUE TITLE
bug: lots of requests on arbitrum

### ISSUE THREAD

**Issue by chillichelli** [wagmi-dev/wagmi#962] opened 2022-09-17 15:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.5.12

### Current Behavior

If your wallet is connected to arbitrum and you connect on the app using the InjectedConnector, I see a lot of network requests being fired by useContractReads whereas if im connected to Ethereum but pass chainId: 42161, theres only a couple.

### Expected Behavior

I would expect the same amount of requests being fired

### Steps To Reproduce

On the sandbox press connect and use the console network inspector to see the requests being fired.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/quizzical-goldwasser-6lwu14?file=/src/App.js

**Comment by matthewlilley** [comment] 2022-09-17 22:23
After 30s I have 2k request in the queue for single use contract reads like this. We noticed a huge performance degradation on SushiXSwap in the past week, and this seems to be the root cause. I'm unsure if some changes to wagmi/core are causing this because we didn't run into it until recently, and even pinning wagmi to 0.5.12 doesn't seem to help at all.

**Comment by matthewlilley** [comment] 2022-09-18 14:27
More minimal example here:

https://codesandbox.io/s/nervous-ben-i3fhfn?file=/src/App.js

You have to connect wallet and make sure you're on Arbitrum.

A single balanceOf call proxied via useContractReads results in 16 requests,

1 eth_blockNumber and 15 duplicate eth_calls. I'd expect in this case to only see a maximum of 2 requests?

This gets out of hand quickly when you have large multicall requests, or multiple useContractReads on a single page.

**Comment by jxom** [comment] 2022-10-19 02:19
Fixed in `0.6.7`.

**Closed by jxom** 2022-10-19 02:19 UTC
