### ISSUE TITLE
bug: Connector not found

### ISSUE THREAD

**Issue by kelokchan** [wagmi-dev/wagmi#838] opened 2022-08-11 15:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.2

### Current Behavior

I'm getting `Connector not found` error everytime I try to connect to metamask within the Metamask App browser on Android

### Expected Behavior

Expect connect dialog to show up in metamask

### Steps To Reproduce

- Open Metamask App on Android
- Visit the codesandbox and press metamask button

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/wagmi-test-forked-v5qi39

**Comment by franzwarning** [comment] 2022-08-16 20:26
Also seeing this issue iOS, MetaMask 5.5.0

**Comment by jxom** [comment] 2022-09-08 20:53
Hey! This one can be fixed by upgrading to the latest version of `wagmi`! Let me know if there are any other issues :)

**Comment by adrianotadao** [comment] 2022-09-22 12:46
hey @kelokchan and @franzwarning I'm wondering if you handled this issue already. Did you?

I'm facing the same problem and as far as I can see, I think we will need to use something like rainbowkit

**Comment by kelokchan** [comment] 2022-09-29 05:04
It has something to do with this [issue](https://github.com/MetaMask/metamask-mobile/issues/3258)

**Comment by toteto** [comment] 2022-10-27 09:33
Opening the example (https://v5qi39.csb.app/) (note: not in the sandbox) worked on my MetaMask Mobile (Android).

**Comment by paOol** [comment] 2022-11-03 01:15
Same issue here,

I have tried the link above on my android device it shows  Metamask (unsupported) and Injected (unsupported).

phone is on android 13.


I also tested my nextjs app locally, and and running 
    "wagmi": "^0.7.5".

Same behavior, when i click metamask or injected nothing happens. However, If I choose walletConnect and click connect it prompts my metamask mobile, as well as trustwallet.

**Closed** 2022-11-09 17:16 UTC

**Comment by tmm** [comment] 2022-11-09 22:00
@paOol I'm not able to reproduce on web or iOS. What version of Android and MM Android app are you using?

**Comment by paOol** [comment] 2022-11-15 15:12
MM v5.9.1
android 13

**Comment by vildantursic** [comment] 2022-11-17 18:02
I can confirm issue, but I've noticed that it works without any problems within MetaMask browser. And it only appears on mobile, desktop is fine.

**Comment by youthinn** [comment] 2023-05-11 16:34
![image](https://github.com/wagmi-dev/wagmi/assets/96770326/b97d256c-47cd-4336-ad17-8fdf763992dd)
Is there a workaround, I want to send a transaction after connecting to the wallet using wagmi and also prompts this error

**Comment by tmm** [comment] 2023-05-11 17:12
@youthinn this issue is from a while ago. Please open a new issue with a minimal reproducible example.

**Comment by vinhyenvodoi98** [comment] 2023-06-14 15:31
i got same issue but just logout and login wallet again to solve problem

**Comment by starriv** [comment] 2023-06-15 22:54
![image](https://github.com/wagmi-dev/wagmi/assets/7098001/eb4e9ccd-87c7-4b19-860f-f3d76ddd8d0b)
![image](https://github.com/wagmi-dev/wagmi/assets/7098001/a68764a5-9fab-47f7-a400-b8af8f2a1d4b)

The issue still persists. This error report was captured by Sentry and includes user device information. It appears to be specific to the Android platform.

**Comment by mizginstlm** [comment] 2023-11-01 21:50
There can be several reason maybe your key is wrong or if else statement can be working incorrectly for connection, last one your installed package's version is wrong.

**Comment by ArmmGh** [comment] 2023-11-02 22:47
Is there any workaround about this issue please?
Having the same problem on Android device saying "Connector not found"

**Comment by ArmmGh** [comment] 2023-11-02 22:48
> ![image](https://user-images.githubusercontent.com/7098001/246266900-eb4e9ccd-87c7-4b19-860f-f3d76ddd8d0b.png) ![image](https://user-images.githubusercontent.com/7098001/246266966-a68764a5-9fab-47f7-a400-b8af8f2a1d4b.png)
> 
> The issue still persists. This error report was captured by Sentry and includes user device information. It appears to be specific to the Android platform.
> 
> My temporary workaround is to use ` window?.ethereum?.enable()` to ensure connectivity with the wallet on the Android version of Metamask.

but do you have window.ethereum on Android Metamask App Browser? I do not have it at any point, always undefined

**Comment by supra-jatinjainsaraf** [comment] 2023-11-06 11:08
I am also facing the same issue in the browser its working just fine using the extension but on android it showing error

app-index.js:31 ConnectorNotFoundError: Connector not found
    at MetaMaskConnector.connect (webpack-internal:///(app-pages-browser)/./node_modules/@wagmi/connectors/dist/metaMask.js:88:15)
    at async connect (webpack-internal:///(app-pages-browser)/./node_modules/@wagmi/core/dist/chunk-TSH6VVF4.js:732:18)

**Comment by ArmmGh** [comment] 2023-11-06 12:39
I found how to solve the issue for my case.
FIX: Need to have `https` protocol on your server so it works with mobile android, in my case it was deployed on netlify therefore 
it has https and it worked.

**Comment by kkharji** [comment] 2023-11-08 04:34
> I found how to solve the issue for my case. **FIX:** Need to have `https` protocol on your server so it works with mobile android, in my case it was deployed on netlify therefore it has https and it worked.
> 
> so Metamask app injects `window.ethereum` only on https websites as far as I understood

Sadly not in my case it, the protocol is https and still `window.ethereum` is undefined
