### ISSUE TITLE
Building with wagmi-core > 0.8.2 results in an error

### ISSUE THREAD

**Issue by osis** [wagmi-dev/wagmi#1515] opened 2022-12-16 22:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.4

### Current Behavior

Bumping my lib to from 0.8.2 to 0.8.4 results in...

```bash
node_modules/@wagmi/connectors/dist/injected.d.ts:1:50 - error TS2307: Cannot find module '@wagmi/core/dist/index-971cda79' or its corresponding type declarations.

import * as _wagmi_core_dist_index_971cda79 from '@wagmi/core/dist/index-971cda79';
```

When checking out the references and building, I do see...
```typescript
import * as _wagmi_core_dist_index_971cda79 from '@wagmi/core/dist/index-971cda79';
import { Chain } from '@wagmi/core/chains';
import { Address } from 'abitype';
import { providers } from 'ethers';
import { C as Connector } from './base-6b5431a5.js';
import 'eventemitter3';
```

### Expected Behavior

With 0.8.2, there are no build errors.

### Steps To Reproduce

package.json
```diff
 "dependencies": {
-    "@wagmi/core": "^0.8.2",
+    "@wagmi/core": "0.8.4"
   },
  },
```

```npm run build```

**Comment by jxom** [comment] 2022-12-17 05:34
Thanks for reporting. This issue is temporarily closed as I was unable to reproduce. A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via a CodeSandbox (feel free to use [this template](https://codesandbox.io/s/bitter-wind-pv0hwj)) would help a lot. Will reopen once one is provided.

**Closed by jxom** 2022-12-17 05:34 UTC
