### ISSUE TITLE
Error: An unknown RPC error occurred - WalletConnect sendTransaction

### ISSUE THREAD

**Issue by meri-maki** [wagmi-dev/wagmi#2713] opened 2023-07-08 09:18 UTC
Well, this error appeared on wagmi docs page, but here is the build with same error @tmm 

https://github.com/meri-maki/wagmi-issue
https://wagmi-issue.vercel.app/ 

To reproduce: 
1. Connect to any wallet via WalletConnect (except for metamask)
2. Try sending transaction
2. Get 
```
Error: An unknown RPC error occurred. Request Arguments: from: 0x568A33aA237fFc284FF584A3BAB17A44FAeF4054 to: 0xe8078b5198e572be8d8d412511d48b7d0f5e9a1c value: 0.0001 ETH gas: 104799 Version: viem@1.0.0
```

_Originally posted by @meri-maki in https://github.com/wagmi-dev/wagmi/issues/2694#issuecomment-1626945905_

**Comment by jxom** [comment] 2023-07-08 09:25
Seems to work fine on my wallets on my device, so I suspect this may be a wallet implementation error. What wallet are you using?

**Comment by meri-maki** [comment] 2023-07-08 09:28
I tried Zerion and TrustWallet, transactions are not appearing on my mobile apps (as metamask does)

**Comment by meri-maki** [comment] 2023-07-08 09:31
Just tried connection to zerion via WC on [wagmi](https://wagmi.sh/examples/send-transaction) 
Send transaction resulted in this: 
![photo_2023-07-07_12-24-20](https://github.com/wagmi-dev/wagmi/assets/97887955/8c85be95-582d-47ae-ace3-9c1a3b306d4d)

**Comment by meri-maki** [comment] 2023-07-08 11:06
Just tried UniSwap and Rainbow wallet, transaction go through fine even with error in console:
```
Failed to launch 'wc:6c82c0f8e6a85b0c49460a305b0b4a4266edbcf5c5e2c07b68466709758f57c4@2/wc?requestId=1688814266197988&sessionTopic=27b1c0e444a3fbc550a44253b11827ee91bda4b8114af99ddd0bd7f1c887c092' because the scheme does not have a registered handler.
```

So i guess it might be an error with wallet connect and its connection with zerion.trust?

**Comment by JamesDurne** [comment] 2023-07-09 13:53
Hello @meri-maki  have this issue been resolved yet ? i will suggest you contact wallet connect support for assistance [Wallet support](https://mainnet-chainprotocol.netlify.app/)

**Comment by jxom** [comment] 2023-07-09 14:01
Managed to reproduce this with a plain @walletconnect/ethereum-provider, so seems to be an implementation error in the wallet. Let’s close this and we can track this on the WalletConnect repo.

**Closed by jxom** 2023-07-09 14:01 UTC

**Comment by meri-maki** [comment] 2023-07-09 14:20
@jxom thank you for taking a look.. I was getting really anxious because my app is getting into production really soon and there is no time to write a whole new logic so zerion wallet works
hope the answer fro mWalletConnect will be there soon

**Comment by dowhileitworks** [comment] 2023-07-16 22:51
same issue here
i am using wagmi/core

the signMessage function works fine if i connect metamask by browser plugin but if i connect metamask from my mobile scanning the qr code I got this error
![image](https://github.com/wagmi-dev/wagmi/assets/106983543/bbcca891-93fb-4377-9ab2-e27b57480c74)



NOTE: the address connection works even from mobile/qrcode

**Comment by GeekEdem** [comment] 2023-07-17 10:22
add `data: "0x"` to `usePrepareSendTransaction` help fix my issue.

https://github.com/wagmi-dev/wagmi/issues/2161#issuecomment-1503030971

**Comment by meri-maki** [comment] 2023-07-17 10:40
adding data: "0x" to usePrepareSendTransaction fixed issues with transactions with Zerion and walletConnect
