### ISSUE TITLE
bug: hardhat must be installed to use Hardhat plugin

### ISSUE THREAD

**Issue by LilaRest** [wagmi-dev/wagmi#2846] opened 2023-08-01 21:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

For [this app](https://github.com/ledgity-labs/Ledgity-DeFi) we rely on the `hardhat` plugin from `@wagmi/cli/plugins` and on `wagmi generate`.

Running `wagmi generate` locally works fine. But since a few days/weeks it stopped working in CI environment and fails with error `hardhat must be installed to use Hardhat plugin`.

So I expect this bug has been else introduced in recent Wagmi versions as we don't have modified Wagmi CLI stuff since at least a month.

I've seen issue #1877 which seems related.

### Expected Behavior

As you can see in this CI log, `hardhat` looks properly installed, so I would expect Wagmi CLI not failing because of missing hardhat installation.

```
(HIDDEN PART)
[11:15:24.517] dependencies:
(HIDDEN PART)
[11:15:24.518] - @wagmi/core 1.3.7
[11:15:24.518] + @wagmi/core 1.3.8
[11:15:24.518] - viem 1.2.14
[11:15:24.518] + viem 1.4.2
[11:15:24.518] - wagmi 1.3.8
[11:15:24.518] + wagmi 1.3.9
(HIDDEN PART)
[11:15:24.518] 
[11:15:24.518] devDependencies:
(HIDDEN PART)
[11:15:24.519] - hardhat 2.16.1
[11:15:24.519] + hardhat 2.17.0
[11:15:24.519] + hardhat-contract-sizer 2.10.0
(HIDDEN PART)
[11:15:24.520] 
[11:15:24.542] Done in 21.6s
[11:15:24.569] Detected Next.js version: 13.4.9
[11:15:24.655] Running "pnpm run build"
[11:15:25.171] 
[11:15:25.171] > ledgity-defi@1.124.2 build /vercel/path0
[11:15:25.171] > pnpm cc:compile && next build
[11:15:25.171] 
[11:15:25.674] 
[11:15:25.674] > ledgity-defi@1.124.2 cc:compile /vercel/path0
[11:15:25.674] > hardhat compile && wagmi generate && ts-node ./contracts/extract-abis.ts
[11:15:25.674] 
[11:15:26.710] Downloading compiler 0.8.18
[11:15:31.104] Generating typings for: 42 artifacts in dir: typechain-types for target: ethers-v6
[11:15:33.455] Successfully generated 126 typings!
[11:15:33.462] Compiled 42 Solidity files successfully
[11:15:34.118] - Validating plugins
[11:15:34.929] hardhat must be installed to use Hardhat plugin.
[11:15:34.929] To install, run: pnpm add hardhat
```

### Steps To Reproduce

1) Rely on `hardhat` plugin for Wagmi CLI in `wagmi.config.ts`
2) Call `wagmi generate` from a Github workflow file

**Comment by tmm** [comment] 2023-08-01 22:28
Wagmi CLI hasn't [released any new code since June 25th](https://github.com/wagmi-dev/wagmi/releases/tag/%40wagmi%2Fcli%401.3.0). CI issues are tough to work on without a minimal reproducible example so closing until one is added. Some additional questions in the meantime:

- What version of `@wagmi/cli` are you using?
- What package manager are you using? Monorepo?
- Have you changed anything with your CI setup?

**Closed by tmm** 2023-08-01 22:28 UTC

**Comment by LilaRest** [comment] 2023-08-02 09:48
@tmm Oh ok! I'll investigate more the issue and will provide you with a minimal reproduction then.
- Wagmi version: `1.3.0`
- Package manager: `pnpm`
- Monorepo: No
- Changes in CI setup: Not recently (2 months ago)

**Comment by LilaRest** [comment] 2023-08-02 10:09
I think this is also important to mention that it fails in Vercel CD environment.

**Comment by mpaler** [comment] 2023-12-04 19:23
see https://github.com/egoist/detect-package-manager/issues/13
