### ISSUE TITLE
bug: Cannot find name 'AbiParameter'

### ISSUE THREAD

**Issue by BastionProvider** [wagmi-dev/wagmi#1381] opened 2022-11-28 16:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.4

### Current Behavior

I already reported this in Issue [https://github.com/wagmi-dev/wagmi/issues/1306](https://github.com/wagmi-dev/wagmi/issues/1306 ) but the fix that was performed was not able to fix the issue in its entirety. The @wagmi package still has needs to be manually updated from `AbiParameter` to `abitype.AbiParamater` to fix the error.

### Expected Behavior

runs smoothly after `npm install` without any errors and manual fixes in the node_modules folder

### Steps To Reproduce

`npm install wagmi` then `npm run build`

**Comment by tmm** [comment] 2022-12-01 23:12
Just tried looking into this for `wagmi@0.8.8` and wasn't able to find anything (looks like `AbiParameter` is resolving correctly in the build without `abitype.*`).

Can you post a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) with some info on how to reproduce this issue, and then reopen this issue?

**Closed by tmm** 2022-12-01 23:12 UTC
