### ISSUE TITLE
bug: DOMException: Failed to execute 'setItem' on 'Storage'

### ISSUE THREAD

**Issue by roninjin10** [wagmi-dev/wagmi#2182] opened 2023-04-14 05:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.12.10

### Current Behavior

Deleting entire app for just rainbowkit `<WagmiConfig><Button />< /WagmiConfig>` while debugging an issue I noticed this error. 

```
react_devtools_backend.js:2655 DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'wagmi.cache' exceeded the quota.
    at Object.setItem (http://localhost:5173/node_modules/.vite/deps/chunk-KQEOP6FN.js?v=232505ef:745:19)
    at trySave (http://localhost:5173/node_modules/.vite/deps/chunk-46MMT6BX.js?v=232505ef:81:17)
    at http://localhost:5173/node_modules/.vite/deps/chunk-46MMT6BX.js?v=232505ef:90:21
    at http://localhost:5173/node_modules/.vite/deps/chunk-46MMT6BX.js?v=232505ef:129:9
```

[This is my wagm.cache](https://gist.github.com/roninjin10/f002dcfb4f7e957f5828cd0691fd22e4)

My wagmi store
```
{
    "state": {
        "data": {}
    },
    "version": 2
}
```

### Expected Behavior

Not to see that error

### Steps To Reproduce

Use wagmi a lot on a single browser on many accounts?

Or just load my local storage into yours

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

See local storage above

### Anything else?

I searched issues and found an [unanswered discussion](https://github.com/wagmi-dev/wagmi/discussions/1584#discussion-4700390)

**Comment by jxom** [comment] 2023-04-17 02:56
Happy to investigate further if a minimal reproducible example is provided. Will re-open when one is provided.

From first look, looks like the `useConnect` variables are being cached to local storage via React Query, however, these variables should not be cached at all. Perhaps a dapp modifying the query config to cache them in the wagmi store?

**Comment by AdamK222** [comment] 2023-04-21 09:38
Hi, I'm using exactly the same version of wagmi and I face the same error.

I'm using connectkit@1.2.2 as a an overlay for connecting a wallet, this issue appeared just now after upgrading dependencies.

![image](https://user-images.githubusercontent.com/66825147/233602004-406a6940-37eb-4c0f-9e12-e9160d0e4b99.png)

If it starts appearing it is showing again and again every 3 seconds or so.

Refreshing the site helps stop it, but after making a transaction it is back.

I strongly suppose it is because it tries to exceed the local storage limit, I have some of my own savings in local storage which are more imporant than this cache, so if my own cannot be saved I need to find a way to disable or truncate the cache. It saves enormous amount of data.

![image](https://user-images.githubusercontent.com/66825147/233602962-ef410ce7-2438-4836-b786-f30dfc098be5.png)

**Comment by AdamK222** [comment] 2023-04-21 09:39
If you want to reproduce it you need to make a lot of transactions that way they are saved into wagmi cache, that's what I suppose, please re-open this issue

**Comment by jxom** [comment] 2023-06-27 20:30
Closing as React Query persister overflow should be handled by React Query.

**Closed by jxom** 2023-06-27 20:30 UTC

**Comment by tremarkley** [comment] 2023-08-03 01:41
I came across an issue with using the wagmi cache along with having `BigNumber`s in my react query state. In order to fix this issue I am considering turning off caching. @AdamK222 I believe the cache can be turned off by passing in the `storage` parameter to the `createConfig` function like so:

```
import { createConfig, createStorage } from 'wagmi'

export const noopStorage: BaseStorage = {
  getItem: (_key) => '',
  setItem: (_key, _value) => null,
  removeItem: (_key) => null,
}

const storage = createStorage({
  storage: noopStorage,
})

createConfig({
 storage
})
```

**Comment by vm06007** [comment] 2023-09-14 10:23
any suggestions on what would be the best way (or any other alternatives) on how to fix it or resolve this?

**Comment by vm06007** [comment] 2023-09-14 13:22
> I came across an issue with using the wagmi cache along with having `BigNumber`s in my react query state. In order to fix this issue I am considering turning off caching. @AdamK222 I believe the cache can be turned off by passing in the `storage` parameter to the `createConfig` function like so:
> 
> ```
> import { createConfig, createStorage } from 'wagmi'
> 
> export const noopStorage: BaseStorage = {
>   getItem: (_key) => '',
>   setItem: (_key, _value) => null,
>   removeItem: (_key) => null,
> }
> 
> const storage = createStorage({
>   storage: noopStorage,
> })
> 
> createConfig({
>  storage
> })
> ```

this seems to lead needing to reconnect wallet every time after revisiting the dapp or reloading page

**Comment by vm06007** [comment] 2023-09-14 13:58
here is another way to replicate this issue that should be reopened and resolved: 

first define your contracts array to use in useContractRead when you want to read 10 different function values from the same contract (or 2 different contracts, maybe 5 different function values from each)

```
    const contracts = [
        {
            chainId,
            abi: CONTRACT_ABI_A,
            address: ADDRESS_A,
            functionName: "someFunctionNameA",
            args: [someArgs],
        },
        {
            chainId,
            abi: CONTRACT_ABI_B,
            address: ADDRESS_B,
            functionName: "someFunctionNameB",
            args: [someArgs],
        },
        {
            chainId,
            abi: CONTRACT_ABI_A,
            address: ADDRESS_A,
            functionName: "someFunctionNameC",
            args: [someArgs],
        },
        {
            chainId,
            abi: CONTRACT_ABI_B,
            address: ADDRESS_B,
            functionName: "someFunctionNameD",
            args: [someArgs],
        },

```

if you have this array maybe trying to read 10 different function names through useContractReads (which is a wrapper around multicall) and for each you pass ABI as entire ABI of the contract it will clonk up the space pretty quick trying to store ABI in the `wagmi.cache`

just try to pass it further and you can replicate this

```
    const { isLoading } = useContractReads({
        allowFailure: true,
        watch: true,
        enabled,
        contracts // here we pass this array
        .....

```

issue is that `CONTRACT_ABI_A` and `CONTRACT_ABI_B` could be pretty huge files with all functions reused every time
the only solution I've found is to chop of the ABIs separate them into small chunks to use only small portion for each entry in the `contracts` array before passing it to `useContractReads`

**Comment by vm06007** [comment] 2023-09-14 13:59
for @jxom to consider reopening

**Comment by vm06007** [comment] 2023-09-15 05:41
so if you just follow this example here: https://wagmi.sh/react/hooks/useContractReads#functionname-optional
![Screenshot 2023-09-15 at 12 39 52 PM](https://github.com/wagmi-dev/wagmi/assets/1138692/7d391e1c-f3b3-48da-b547-530b9321b83e)

and expand this example to maybe read 10 functions (example only shows 2) as function list grows notice how each item in the array uses `abi: wagmigotchiABI` and its not reused, bur rather then stored in wagmi.catche so you will eventually run into this issue with = Failed to execute 'setItem' on 'Storage'  depending how big is that abi that gets pushed over and over instead of have ability to reuse or avoid duplicate

**Comment by tmm** [comment] 2023-09-15 12:08
See https://github.com/wagmi-dev/wagmi/issues/2182#issuecomment-1610170942

**Comment by vm06007** [comment] 2023-09-16 13:26
you could fix this on wagmi side easily though

**Comment by iam4x** [comment] 2023-09-25 10:07
This is breaking my whole app, can we implement some sort of async storage and use something better than localStorage?
I can't save new values in localStorage from my app logic.

**Comment by iam4x** [comment] 2023-09-25 10:19
In the meantime, I've patched re-creating the storage and limited it's entries:

![image](https://github.com/wagmi-dev/wagmi/assets/893837/6a92f96d-d681-4b66-b13c-73af310328de)

**Comment by Dalcor** [comment] 2023-12-01 14:10
Any updates on this?

**Comment by bconfortin** [comment] 2023-12-07 18:39
Getting the same issue. Any news?

**Comment by michaelcohen716** [comment] 2023-12-25 02:36
hitting this as well. onchain read loads value and then deletes it strangely
